import { SingleTweet,currentUserAction } from "./currentUserReducer";
import currentUserActionTypes from "./currentUserActionTypes.";
const currentUserAction={
    setData:(data:[SingleTweet]):currentUserAction=>{
        return{
            type:currentUserActionTypes.SET_DATA,
            payload:data
        }
    },
    setAddUser:(data:string):currentUserAction=>{
        return{
            type:currentUserActionTypes.SET_ADD_USER,
            payload:data
        }
    },
    setDelUser:(data:string):currentUserAction=>{
        return{
            type:currentUserActionTypes.SET_DEL_USER,
            payload:data
        }
    },
    setAddKeyword:(data:string):currentUserAction=>{
        return{
            type:currentUserActionTypes.SET_ADD_KEYWORD,
            payload:data
        }
    },
    setDelKeyword:(data:string):currentUserAction=>{
        return{
            type:currentUserActionTypes.SET_DEL_KEYWORD,
            payload:data
        }
    },
    incrPage:():currentUserAction=>{
        return{
            type:currentUserActionTypes.INCR_PAGE,
            payload:""
        }
    },
    dcrPage:():currentUserAction=>{

        return{
            type:currentUserActionTypes.DCR_PAGE,
            payload:""
        }
    },
    setAllKeywords:(data:string):currentUserAction=>{
        return{
            type:currentUserActionTypes.SET_ALL_KEYWORDS,
            payload:data
        }
    },
    setViolentPercentage:(data:number):currentUserAction=>{
        return{
            type:currentUserActionTypes.SET_VIOLENT_PERCENTAGE,
            payload:data
        }
    },
    setNviolentPercentage:(data:number):currentUserAction=>{
        return{
            type:currentUserActionTypes.SET_NVIOLENT_PERCENTAGE,
            payload:data
        }
    },
    setIsUserMonitorTrue:():currentUserAction=>{
        return{
            type:currentUserActionTypes.SET_USER_MONITOR_TRUE,
            payload:''
        }
    },
    setIsUserMonitorFalse:():currentUserAction=>{
        return{
            type:currentUserActionTypes.SET_USER_MONITOR_FALSE,
            payload:''
        }
    }
}

export default currentUserAction;